### ISSUE TITLE
Fix sidebar menu click problem

### ISSUE THREAD

**Issue by ghost** [SoloTechno/SoloWaterAndroid#11]
Solve a problem with clicking sidebar menus on Google Map display

**Comment by anushkmittal** [comment]
@joshua31101 is this still a problem?

**Comment by anushkmittal** [comment]
BTW, what's the bug here?

**Comment by ghost** [comment]
@anushkmittal  It is now fixed. There was a problem that menus such as edit profile and water report were unable to be clicked.
