### ISSUE TITLE
Edit profile crashes / not working

### ISSUE THREAD

**Issue by anushkmittal** [SoloTechno/SoloWaterAndroid#4]
- DB not set up for edit profile nor does registration updates DB
- Nor does edit profile work

**Comment by anushkmittal** [comment]
Can you look over it and see if everything works as expected?

**Comment by anushkmittal** [comment]
This might help: http://www.androidhive.info/2016/10/android-working-with-firebase-realtime-database/

**Comment by Timbabs** [comment]
Working on that now

**Comment by Timbabs** [comment]
Done!!
